alias sshody="ssh  -Y -C -o ServerAliveInterval=30 -fN ody"
alias sshorch="ssh -Y -C -o ServerAliveInterval=30 -fN orch"
# ignore a bunch of common history commands
export HISTIGNORE="&:ls:[bf]g:exit"

# use color LS
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# use some nice bash options
#set -o noclobber
set -o vi

#add ssh-agent

if [ `hostname -s` == "miro" ] ; then
 source ~/myconfig/bash/ssh-find-agent/ssh-find-agent.bash
 set_ssh_agent_socket
fi

##BEGIN GIT##
# Set config variables first
#GIT_PROMPT_ONLY_IN_REPO=1
# as last entry source the gitprompt script
#source ~/.bash-git-prompt/gitprompt.sh
function parse_git_branch () {
       git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

RED="\[\033[0;31m\]"
YELLOW="\[\033[0;33m\]"
GREEN="\[\033[0;32m\]"
BLUE="\[\033[0;34m\]"
MAG="\[\033[0;35m\]"
NO_COLOUR="\[\033[0m\]"

PS1="$YELLOW\u@\h$GREEN:\w$MAG\$(parse_git_branch)$NO_COLOUR\$ "
#PS1="\e[0;33m\u@\h:\e[m \e[0;35m\w\e[m\a$ "

alias gpom='git pull origin master'
alias ghom='git push origin master'
alias gpum='git pull upstream master'
alias gcu='git checkout -b upstream upstream/master'

function gitjoin(){
       
 git rebase -i HEAD~"$1"      
       
}

function gcom(){
 echo file  $1
 echo message $2
 git add $1
 git commit -m "$2"
}

function gitlog(){
       
 git config --global alias.lg "log --color --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --name-status"

}

source ~/myconfig/bash/git-completion.bash

##END GIT##

# use a color terminal
# export TERM="screen-256color"

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# don't overwrite GNU Midnight Commander's setting of `ignorespace'.
HISTCONTROL=$HISTCONTROL${HISTCONTROL+:}ignoredups
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize


# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
# some more ls aliases
alias ll='ls -lh'
alias la='ls -A'
alias l='ls -CF'
alias bt='byobu-tmux'

#bashaggent alias
alias upagent='eval "$(ssh-agent -s)";ssh-add'

# export PATH=~/bin:$PATH

# customr alias
alias e='emacsclient -t'
alias ec='emacsclient -c'
alias remove_blank_lines="sed -i '/^$/d'"
alias sq='squeue -u lpantano'
alias sb='sbatch'
alias bs='bsub'
alias bj='bjobs'
# bcbio files
bcbdebug='log/bcbio-nextgen-debug.log'
bcblog='log/bcbio-nextgen.log'
bcbcmd='log/bcbio-nextgen-commands.log'

